### ISSUE TITLE
Electron 취약점 대응

### ISSUE THREAD

**Issue by Lastorder-DC** [thy2134/ElecTwitch#18]
[취약점 정보](https://electronjs.org/blog/protocol-handler-fix)

윈도우 버전만 취약점이 발견되었다고 합니다.

**Comment by kyujin-cho** [comment]
안그래도 깃헙 메인에 해당 취약점 관련 내용이 올라와 있네요.
현재 소스코드를 전체적으로 들어올리는 중이라, 다음 커밋까지 시간이 걸릴 듯 합니다.
다음 커밋 때 업데이트 하겠습니다.

**Comment by rishubil** [comment]
처리하실때까지는 이슈 닫지 않고 오픈해두시는게 더 낫지 않을까요?

**Comment by kyujin-cho** [comment]
아 그러면 오픈해두겠습니다.

**Comment by kyujin-cho** [comment]
README에 해당 내용을 추가하는 [커밋](https://github.com/thy2134/ElecTwitch/commit/a2625334564e34fc72ca16375e10945d062aa909)을 올렸습니다.

**Comment by kyujin-cho** [comment]
해당 내용을 대응하는 커밋을 올렸습니다. 이슈는 닫습니다.
