### ISSUE TITLE
지원하는 Node.js 버전?

### ISSUE THREAD

**Issue by rishubil** [thy2134/ElecTwitch#7]
지원하는 Node.js 버전 범위나 타겟 버전이 있나요?

**Comment by kyujin-cho** [comment]
Nodejs v7, Electron 1.7을 타겟으로 개발했고, Babel로 ES6 문법을 일부 가져왔습니다.

**Comment by rishubil** [comment]
Node.js v7.10.1 에서 정상 동작함을 확인했습니다.
감사합니다.
